# Generated by Django 4.2.1 on 2023-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('transcribe', models.TextField(blank=True)),
            ],
        ),
    ]
